// <auto-generated />
namespace NFC_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddZamowinie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddZamowinie));
        
        string IMigrationMetadata.Id
        {
            get { return "201808081421203_AddZamowinie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
